
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-18T10:04:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cc0fda8176bfebbcc3ec071ceb580ca343bfaa3",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
