
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T19:15:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b8a307f082d44b90b172709fd1772d95a2689cf",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
