
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-09T15:57:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0676ca0620c07b3d7bdff9541650e96ad7c36c1f",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
